# Generated by Django 5.2.7 on 2025-10-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_course_created_at_course_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
