# Generated by Django 5.2.7 on 2025-10-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_course_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_course',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_course',
            field=models.ManyToManyField(blank=True, to='student.course'),
        ),
    ]
