# Generated by Django 5.2.7 on 2025-10-23 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_studentprofile_student_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_course',
            field=models.ManyToManyField(blank=True, through='student.StudentCourse', to='student.course'),
        ),
    ]
