# Generated by Django 5.2.7 on 2025-10-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentcourse_alter_studentprofile_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_course',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_courses',
            field=models.ManyToManyField(blank=True, related_name='students', through='student.StudentCourse', to='student.course'),
        ),
    ]
